### ISSUE TITLE
Stuck in yujin_ocs part when "bash setup_kinetic.bash" in Ubuntu16.04

### ISSUE THREAD

**Issue by NanxunDuo** [erlerobot/gym-gazebo#45]
I am successfully go through all the steps before "bash setup_kinetic.bash", and I have used _**sudo apt-get install ros-kinetic-yujin-ocs**_ to install yujin-ocs and it still went wrong like this
 
![default](https://user-images.githubusercontent.com/33029582/31922823-d57b9140-b8a9-11e7-8ffc-9c1f78cc5caf.png)

Anyone have ideas about solving this?
Many thnks!!

**Comment by swordsgnat** [comment]
I had a problem with the same package - it seems like something's just not right with it. That said, it also seems pretty teriatry. I `CATKIN_IGNORE`d `yocs_ar_marker_tracking` and `yocs_ar_pair_tracking` within `yujin_ocs` the same way you have to for the other three packages in the tutorial, and then the bash ran properly. 

Grain of salt, because I still haven't gotten the tutorial to work (currently stuck on a "no module named gym_gazebo" bug) but that might help you past that part.

**Comment by kentsommer** [comment]
@NanxunDuo 

Your actual issue is higher up in the build. Please scroll up and look for the first error.

**Comment by NanxunDuo** [comment]
@kentsommer 
![2017-11-01 11-24-15](https://user-images.githubusercontent.com/33029582/32259075-02eac330-bef9-11e7-9382-54ccb60a3b0e.png)

This is my very first error running bash setup_kinetic.bash.
And the last error has changed to lack of packages tf2_sensor_msgs
![default](https://user-images.githubusercontent.com/33029582/32259011-aed64d78-bef8-11e7-8cab-ce5cd1b7b8e2.png)
So could you please help me to tell what is the exact error?

**Comment by kentsommer** [comment]
@NanxunDuo 

1. You can fix these errors by editing the gazebo.repos file which can be found at gym_gazebo/envs/installation and adding adding the following (in place of the other two alvar related entries)
```
ar_track_alvar:
   type: git
   url: https://github.com/ros-perception/ar_track_alvar.git
   version: kinetic-devel
```

2. Also add this to the above file in place of the other mav_comm entry
```
mav_comm:
   type: git
   url: https://github.com/ethz-asl/mav_comm.git
   version: master
```
